mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from personal.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', account_view, name='account'),
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),
    path('news/', include('news.urls', 'news')),
    path('register/', registration_view, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from news.views import (
	create_news_view,
	detail_news_view,
	edit_news_view,
)

app_name = 'news'

urlpatterns = [
    path('create/', create_news_view, name="create"),
    path('<slug>/', detail_news_view, name="detail"),
    path('<slug>/edit/', edit_news_view, name="edit"),
 ]

personal/models.py
from django.db import models
# Create your models here.

# PRIORITY = [('H', 'High'),
#             ('M', 'Medium'),
#             ('L', 'Low')]

# class Question(models.Model):
#     title                   = models.CharField(max_length=60)
#     question                = models.TextField(max_length=400)
#     priority                =models.CharField(max_length=1, choices=PRIORITY)
    
#     def __str__(self):
#         return self.title
    
#     class Meta:
#         verbose_name = "the Question"
#         verbose_name_plural = "Peoples Questions"

personal/views.py
from django.shortcuts import render
from operator import attrgetter

from news.models import NewsPost



def home_screen_view(request):
	
	context = {}
	news_posts = sorted(NewsPost.objects.filter(published__gt=0), key=attrgetter('date_updated'), reverse=True)
	context['news_posts'] = news_posts

	return render(request, "personal/home.html", context)

personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	@media (max-width: 768px) {
		.right-column {
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) {
		.right-column {
			margin-left: 20px;
		}
	}

	.news-post-container {
		margin-bottom: 20px;
		width: 100%;
	}

	.create-post-bar {
		background-color: #fff;
		margin-bottom: 20px;
	}

	.left-column {
		padding: 0px;
	}

	.right-column {
		padding: 0px;
	}

	.lead {
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<div class="left-column col-lg-7 offset-lg-1">

			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'django.png' %}" width="72"
						height="72">
					<p class="lead">IEste é um site de notícias, escrito por usuários como você. Se quiser ler fique a vontade.
					Para poder escrever notícias é necessário se inscrever no site. Faça uma conta grátis agora mesmo e se junte a
					comunidade DJNews!</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'news:create' %}">Criar notícia</a></p>
				</div>
			</div>

			{% for post in news_posts %}
			<div class="news-post-container">
				{% include 'news/snippets/news_post_snippet.html' with news_post=post %}
			</div>
			{% endfor %}
		</div>


		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'django.png' %}" width="72"
					height="72">
				<p class="lead">Este é um site de notícias, escrito por usuários como você. Se quiser ler fique a vontade.
					Para poder escrever notícias é necessário se inscrever no site. Faça uma conta grátis agora mesmo e se junte a comunidade DJNews! </p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'news:create' %}">Criar notícia</a></p>
			</div>

		</div>

	</div>
</div>

{% endblock content %}